apiVersion: batch/v1
kind: Job
metadata:
  name: starter
spec:
  completions: {{ .Values.starter.completions | default 100 }}
  parallelism: {{ .Values.starter.parallelism | default 100 }}
  template:
    metadata:
      labels:
        app: starter
    spec:
      restartPolicy: OnFailure
      containers:
      - name: starter
        image: {{ .Values.starter.image }}:{{ .Values.starter.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - "-target-host=temporal:7233"
