worker:
  image: worker
  tag: latest
  replicas: 1
  port: 8079

starter:
  image: starter
  tag: latest
  completions: 1
  parallelism: 1

prometheus:
  image: prom/prometheus
  tag: latest
  port: 9090

grafana:
  image: grafana/grafana
  tag: latest
  port: 3000
  adminPassword: admin
