worker:
  image: worker
  tag: latest
  replicas: 1
  port: 8079

starter:
  enabled: false  # Set to true to launch starter jobs
  image: starter
  tag: latest
  completions: 100
  parallelism: 100

prometheus:
  image: prom/prometheus
  tag: latest
  port: 9090

grafana:
  image: grafana/grafana
  tag: latest
  port: 3000
  adminPassword: admin
