scrape_configs:
  - job_name: 'temporal-sdk'
    metrics_path: /metrics
    scrape_interval: 5s
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: 
        - host.docker.internal:8079
