scrape_configs:
  - job_name: 'temporal-sdk'
    metrics_path: /metrics
    scrape_interval: 1s
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: 
        - host.docker.internal:8079
  - job_name: 'temporal-cloud'
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_timestamps: true
    scheme: https
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/api_key_metrics
    static_configs:
      - targets: ['metrics.temporal.io']
    metrics_path: '/v1/metrics'